# Welcome to Jekyll!
#

# Site settings
title: Lalo Developer
description: |
  I am a computer systems engineering student, 
  I love programming and creating real problem solutions
owner: Eduardo Garcia Laguna # or company name
first_published: 2020 # if migrating another site, the year of your first publish
email: elalo417@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://google.com" # the base hostname & protocol for your site
social:
  twitter: https://twitter.com/elalo417
  github: https://github.com/elalo4171
  linkedin-square: https://linkedin.com/in/eduardo-laguna-499626183
  facebook-official: https://facebook.com/<username>
  google-plus-square: https://plus.google.com/u/0/+<username>
  #email: /contact/
  #flickr:
  #instagram:
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed
